const user1 = {
    firebaseId: "ThisIsAFakeFirebaseId",
    firstName: "Jamie",
    lastName: "Jamison",
    email: "jamietheman@hotmail.com",
    userPhoto: "http://unsplash.it/100/100",
    zipCode: 92392,
    tacosPerMonth: 5,
    hardOrSoft: "soft",
    cornOrFlower: "flower",
    heatPreference: 5,
    streetOrGourmet: "street",
    favTaco: "chicken",
    favTacoLocation: "Los Cuscos",
    bestTacoMemory: "homemade tacos",
    instaHandle: "Instagram goes here",
    twitterHandle: "twitter goes here",
    facebookPage: "facebook page goes here",
    website: "espn.com"
  }
  const user2 = {
    firebaseId: "ThisIsAFakeFirebaseId1",
    firstName: "Bob",
    lastName: "Jamison",
    email: "jamietheman2@hotmail.com",
    userPhoto: "http://unsplash.it/100/100",
    zipCode: 92392,
    tacosPerMonth: 5,
    hardOrSoft: "soft",
    cornOrFlower: "flower",
    heatPreference: 5,
    streetOrGourmet: "street",
    favTaco: "chicken",
    favTacoLocation: "Los Cuscos",
    bestTacoMemory: "homemade tacos",
    instaHandle: "Instagram goes here",
    twitterHandle: "twitter goes here",
    facebookPage: "facebook page goes here",
    website: "espn.com"
  }
  const user3 = {
    firebaseId: "ThisIsAFakeFirebaseId5",
    firstName: "Kellie",
    lastName: "Jamison",
    email: "jamietheman5@hotmail.com",
    userPhoto: "http://unsplash.it/100/100",
    zipCode: 92392,
    tacosPerMonth: 5,
    hardOrSoft: "soft",
    cornOrFlower: "flower",
    heatPreference: 5,
    streetOrGourmet: "street",
    favTaco: "chicken",
    favTacoLocation: "Los Cuscos",
    bestTacoMemory: "homemade tacos",
    instaHandle: "Instagram goes here",
    twitterHandle: "twitter goes here",
    facebookPage: "facebook page goes here",
    website: "espn.com"
  }
//   const user4 = {
//     firebaseId: "ThisIsAFakeFirebaseId8",
//     firstName: "Jamie",
//     lastName: "Jamison",
//     email: "jamietheman8@hotmail.com",
//     userPhoto: "http://unsplash.it/100/100",
//     zipCode: 92392,
//     tacosPerMonth: 5,
//     hardOrSoft: "soft",
//     cornOrFlower: "flower",
//     heatPreference: 5,
//     streetOrGourmet: "street",
//     favTaco: "chicken",
//     favTacoLocation: "Los Cuscos",
//     bestTacoMemory: "homemade tacos",
//     instaHandle: "Instagram goes here",
//     twitterHandle: "twitter goes here",
//     facebookPage: "facebook page goes here",
//     website: "espn.com"
//   }
//   const user5 = {
//     firebaseId: "ThisIsAFakeFirebaseId9",
//     firstName: "Julie",
//     lastName: "Jamison",
//     email: "jamietheman8@hotmail.com",
//     userPhoto: "http://unsplash.it/100/100",
//     zipCode: 92392,
//     tacosPerMonth: 5,
//     hardOrSoft: "soft",
//     cornOrFlower: "flower",
//     heatPreference: 5,
//     streetOrGourmet: "street",
//     favTaco: "chicken",
//     favTacoLocation: "Los Cuscos",
//     bestTacoMemory: "homemade tacos",
//     instaHandle: "Instagram goes here",
//     twitterHandle: "twitter goes here",
//     facebookPage: "facebook page goes here",
//     website: "espn.com"
//   }
//   const user6 = {
//     firebaseId: "ThisIsAFakeFirebaseId10",
//     firstName: "Jamie",
//     lastName: "Jamison",
//     email: "jamietheman10@hotmail.com",
//     userPhoto: "http://unsplash.it/100/100",
//     zipCode: 92392,
//     tacosPerMonth: 5,
//     hardOrSoft: "soft",
//     cornOrFlower: "flower",
//     heatPreference: 5,
//     streetOrGourmet: "street",
//     favTaco: "chicken",
//     favTacoLocation: "Los Cuscos",
//     bestTacoMemory: "homemade tacos",
//     instaHandle: "Instagram goes here",
//     twitterHandle: "twitter goes here",
//     facebookPage: "facebook page goes here",
//     website: "espn.com"
//   }

  module.exports = {user1, user2, user3} 