const userTest1 = {
    firebaseId: "ThisIsAFakeFirebaseId0",
    id: "5",
    lastName: "Jamison",
    userPhoto: "http://unsplash.it/100/100",
    zipCode: 92392,
    tacosPerMonth: 5,
    hardOrSoft: "soft",
    cornOrFlour: "flour",
    heatPreference: 5,
    streetOrGourmet: "street",
    favTaco: "chicken",
    favTacoLocation: "Los Cuscos",
    bestTacoMemory: "homemade tacos",
    instaHandle: "Instagram goes here",
    twitterHandle: "twitter goes here",
    facebookPage: "facebook page goes here",
    website: "espn.com"
  }
  const userTest2 = {
    firebaseId: "ThisIsAFakeFirebaseId15",
    id: "27",
    firstName: "John",
    lastName: "Jamison",
    email: "john123@hotmail.com",
    userPhoto: "http://unsplash.it/100/100",
    zipCode: 92392,
    tacosPerMonth: 5,
    hardOrSoft: "soft",
    cornOrFlour: "flour",
    heatPreference: 5,
    streetOrGourmet: "street",
    favTaco: "chicken",
    favTacoLocation: "Los Cuscos",
    bestTacoMemory: "homemade tacos",
    instaHandle: "Instagram goes here",
    twitterHandle: "twitter goes here",
    facebookPage: "facebook page goes here",
    website: "espn.com"
  }
  const userTest3 = {
    firebaseId: "ThisIsAFakeFirebaseId33",
    id: "30",
    firstName: "Burt",
    lastName: "Emanuel",
    email: "emanuel123@hotmail.com",
    userPhoto: "http://unsplash.it/100/100",
    zipCode: 92394,
    tacosPerMonth: 5,
    hardOrSoft: "soft",
    cornOrFlour: "flour",
    heatPreference: 5,
    streetOrGourmet: "street",
    favTaco: "chicken",
    favTacoLocation: "Los Cuscos",
    bestTacoMemory: "homemade tacos",
    instaHandle: "Instagram goes here",
    twitterHandle: "twitter goes here",
    facebookPage: "facebook page goes here",
    website: "espn.com"
  }
  // const userTest4 = {
  //   firebaseId: "ThisIsAFakeFirebaseId33",
  //   // id: "30",
  //   firstName: "Juan",
  //   lastName: "Marquez",
  //   email: "Marquez@hotmail.com",
  //   userPhoto: "http://unsplash.it/100/100",
  //   zipCode: 92394,
  //   tacosPerMonth: 5,
  //   hardOrSoft: "soft",
  //   cornOrFlour: "flour",
  //   heatPreference: 5,
  //   streetOrGourmet: "street",
  //   favTaco: "chicken",
  //   favTacoLocation: "Los Cuscos",
  //   bestTacoMemory: "homemade tacos",
  //   instaHandle: "Instagram goes here",
  //   twitterHandle: "twitter goes here",
  //   facebookPage: "facebook page goes here",
  //   website: "espn.com"
  // }

  module.exports = {userTest1, userTest2, userTest3 }